### ISSUE TITLE
Example doesn't really explain how to use this

### ISSUE THREAD

**Issue by Lauriy** [ClearcodeHQ/pytest-redis#183]
I've reverted to just using:
@mock.patch('django.core.cache.cache.get')

**Comment by pasqoo** [comment]
It would be helpful to see how a codebase that uses _pytest_ can integrate the functionalities of _pytest-redis_. Maybe an example that shows some code, some test code, and the conftest.py file.

I have a _flask_ application which uses _Redis_ for the session.
When I run `pytest` I see a bunch of errors related to failed connections to Redis. So I thought of mocking Redis.
Would _pytest-redis_ help in this case, or does it solve a different problem?

**Comment by fizyk** [comment]
@pasqoo it really depends on the tests, how you write them, how you tests them. One thing you need to have before running tests is to determine port numbers before you run tests, either randomly selecting them or otherwise (pytest hook will help you) and after that you need to update flask's config.

Other than that it's either having the port configured as described in README or redefine fixtures using factories in your conftest.

Both flask and django unfortunately are using global contexts which makes it all the harder to test.

**Comment by toyg** [comment]
I think the issue is that, to people not particularly versed in pytest lingo, terse statements like "Simply include one of these fixtures into your tests fixture list" or "Each Redis process fixture can be configured in a different way than the others through the fixture factory arguments", mean very little. A three-line example would be much more helpful. Look to [Pytest-VCR](https://pypi.org/project/pytest-vcr/) for an example of a much-more usable readme.

**Comment by cglacet** [comment]
I'm totally confused to, I just want to make sure my Redis server is up and running to start tests. In other words I want avoid starting the server manually (ie., using a bash script that would then start pytest). Can this package help ? (I guess that makes no difference but I'm using aioredis as client).

**Comment by fizyk** [comment]
@cglacet yes, that is exactly what this plugin is for. And the client your code is using might be whatever you like. 
You use this plugin to start redis (or connect to docker based one), prep data in redis for the test, and after you run test, check (if any) conditions you require about the changes to the data stored in redis.

@toyg As I wrote before, fixtures are such basic concept that I've never thought of including example about how to use fixtures https://docs.pytest.org/en/latest/fixture.html#fixtures-as-function-arguments 
I might as well kind of duplicate the example trying to explain what's happening along the way.

**Comment by fizyk** [comment]
@cglacet @toyg if you could look at the https://github.com/ClearcodeHQ/pytest-redis/pull/235 if that's clear enough

@toyg as for the vcr, I understand why it might be helpful since it uses marks, which are feature that's not used as often as fixtures themselves.
