### ISSUE TITLE
the redisdb factory could accept a scope of the fixture as parameter

### ISSUE THREAD

**Issue by rplevka** [ClearcodeHQ/pytest-redis#248]
### What action do you want to perform
I found myself in a need of a `redisdb` fixture that would use `session` scope instead of the hardcoded `function` one.

I'm trying to use redis for sharing some context between multiple `pytest-xdist` sessions.
`xdist` is limited when it comes to the scoped fixtures as each worker is a standalone pytest runner, thus sharing the fixtures doesn't work.

If the current `redisdb` factory accepted other scopes as a parameter, I could easily use it to create a `session`-scoped redisdb fixtures, which would persist across the whole session, so individual tests can set/get info from it.
The whole  teardown would happen after the session is done.

Although my use case probably doesn't really fit the original purpose of this plugin, this little change would unblock me.

### What are the results
`redisdb` factory returns only a `function`-scoped fixture, which has hardcoded finalizer to wipe out the data from the store after the function is finished.

### What are the expected results
Ability to generate the fixture with different than the default scope.

**Comment by fizyk** [comment]
I don't think that if you need to share context between xdist sessions, you should use fixture starting process for that... it seems like extension to xdist rather than anything else.

If I may, you'd rather need to set up separate redis instance, not necessary started by test fixtures, as each xdist session should create it's own redis process to be used (on randomized port) so you'd be rather surprised by the results you'd achieve. You'd either have context data on different redis processes each for individual xdist session, or data shared between tests, which would make them really unpredictable. 
And imagine a session that  gets assigned tests without redis fixtures, then it won't have context to write to (it might start faster since no tests here)
